<footer>
    <section class="footer-section">
        <h3>Project</h3>
        <ul>
            <li>
                <a href="https://github.com/106225401/applied-web-project-part-1" target="_blank">
                    GitHub Repository (Source Code)
                    <span class="sr-only">(opens in new window)</span>
                </a>
            </li>
            <li>
                <a href="https://student-team-cos10026.atlassian.net/jira/software/projects/AWPP1/boards/4" target="_blank">
                    Jira (Project Management)
                    <span class="sr-only">(opens in new window)</span>
                </a>
            </li>
        </ul>
    </section>

    <section class="footer-section">
        <h3>Quick Links</h3>
        <nav aria-label="Footer navigation">
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Jobs</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About Us</a></li>
            </ul>
        </nav>
    </section>

    <section class="footer-section">
        <h3>Contact Us</h3>
        <p>Email: <a href="mailto:info@nextgen.com">info@nextgen.com</a></p>
    </section>

    <small class="copyright">Copyright &copy; 2026 NextGen Devs. All rights reserved.</small>
</footer>

</body>
</html>